sudo: required
install: true
services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script:
- |
  set -e
    docker build -t langrisha/keybase:latest --build-arg=BUILD_DATE=$(shell date -u "+%Y-%m-%dT%H:%M:%SZ") --build-arg=VCSREF=$(git rev-parse --short HEAD) .
    docker run --rm langrisha/keybase:latest keybase status
